// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdN6W_GrVKRO3_pj7O6iIURgFiWHmK6hc',
    appId: '1:851014778258:web:a7f9e4322b880aac3a554b',
    messagingSenderId: '851014778258',
    projectId: 'auth-chat-app-practice',
    authDomain: 'auth-chat-app-practice.firebaseapp.com',
    storageBucket: 'auth-chat-app-practice.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBecZsrlJq2TiWT60INacL7apo8z976a_A',
    appId: '1:851014778258:android:93774b0c621e05533a554b',
    messagingSenderId: '851014778258',
    projectId: 'auth-chat-app-practice',
    storageBucket: 'auth-chat-app-practice.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOO2mq3mw8ueACwmBnc6aiRCapB9EW1hE',
    appId: '1:851014778258:ios:840046a592deca6e3a554b',
    messagingSenderId: '851014778258',
    projectId: 'auth-chat-app-practice',
    storageBucket: 'auth-chat-app-practice.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOO2mq3mw8ueACwmBnc6aiRCapB9EW1hE',
    appId: '1:851014778258:ios:840046a592deca6e3a554b',
    messagingSenderId: '851014778258',
    projectId: 'auth-chat-app-practice',
    storageBucket: 'auth-chat-app-practice.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAdN6W_GrVKRO3_pj7O6iIURgFiWHmK6hc',
    appId: '1:851014778258:web:edfe53f20a82159b3a554b',
    messagingSenderId: '851014778258',
    projectId: 'auth-chat-app-practice',
    authDomain: 'auth-chat-app-practice.firebaseapp.com',
    storageBucket: 'auth-chat-app-practice.firebasestorage.app',
  );
}
